### ISSUE TITLE
Inconsistent validation results when testing with Jest

### ISSUE THREAD

**Issue by umbertooo** [monterail/vuelidate#384]
A repository with example code can be found here: https://github.com/umbertooo/vuelidate-username-password

After validating a form of two inputs `username` and `password` the css class of these inputs should change according to the validation result. Invalid inputs should be marked with the css class `is-invalid`. A click event on the submit button triggers the validation.

In the linked repository I provided a suite of four tests, that I expected to succeed. (https://github.com/umbertooo/vuelidate-username-password/blob/master/tests/unit/login-form.spec.js)

However in the failing tests `username` is detected correctly as invalid, but `password` is not. This looks inconsistent to me.

Actual test results:
```
 FAIL  tests/unit/login-form.spec.js
  login form
    ✓ should mark username and password as invalid (33ms)
    ✕ should mark inputs as invalid (15ms)
    ✕ should mark inputs as invalid after next tick (5ms)
    ✓ should mark inputs as invalid after forceUpdate (5ms)

  ● login form › should mark inputs as invalid

    expect(array).toContain(value)

    Expected array:
      []
    To contain value:
      "is-invalid"

      20 |
      21 |     expect(wrapper.find("#username").classes()).toContain("is-invalid");
    > 22 |     expect(wrapper.find("#password").classes()).toContain("is-invalid");
         |                                                 ^
      23 |   });
      24 |
      25 |   it("should mark inputs as invalid after next tick", () => {

      at Object.toContain (tests/unit/login-form.spec.js:22:49)

  ● login form › should mark inputs as invalid after next tick

    expect(array).toContain(value)

    Expected array:
      []
    To contain value:
      "is-invalid"

      29 |     return localVue.nextTick().then(() => {
      30 |       expect(wrapper.find("#username").classes()).toContain("is-invalid");
    > 31 |       expect(wrapper.find("#password").classes()).toContain("is-invalid");
         |                                                   ^
      32 |     });
      33 |   });
      34 |

      at toContain (tests/unit/login-form.spec.js:31:51)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 passed, 4 total
Snapshots:   0 total
Time:        1.085s
Ran all test suites.
```

**Comment by laliluna** [comment]
The validation itself apparently works. You can add asserts checking the $error. 
A wrapper.vm.$forceUpdate helps as well. 

Apparently vue cannot see that the $error value has changed

```
 it("should mark inputs as invalid", () => {
    const wrapper = mount(LoginForm, { localVue });

    // validation itself works before and after click

    expect(wrapper.vm.$v.username.$error).toBe(false)
    expect(wrapper.vm.$v.password.$error).toBe(false)
    
    wrapper.find("button").trigger("click");
    
    expect(wrapper.vm.$v.username.$error).toBe(true)
    expect(wrapper.vm.$v.password.$error).toBe(true)

    // a force update fixes the issue as well
    wrapper.vm.$forceUpdate();

    expect(wrapper.find("#username").classes()).toContain("is-invalid");

    expect(wrapper.find("#password").classes()).toContain("is-invalid");
  });
```

**Comment by telmaantunes** [comment]
+1

**Comment by borriej** [comment]
im having a similar issue..
It seems vue validation works async? My ```between: between(0,1)``` is letting a value of ```1.5``` through as valid. 

I have a unit test like:
```
  it('should show error message when price is (1.50) bigger than > 1', async () => {
    const wrapper = mount(MyComponent, {
      stubs: {
        money,
        bFormInvalidFeedback
      },
      propsData: {
        value: 0.25
      },
      store,
      localVue,
      computed: {
        content() {
          return {
            someContentKey: 'error'
          };
        }
      }
    });

    // set stub money price to 1.50
    wrapper.find(money).vm.$emit('input', 1.50);

    wrapper.vm.$forceUpdate();

    expect(wrapper.emitted().input).toBeFalsy();
    expect(wrapper.find('#betweenError').exists());
  });
```
Result is
```
 Expected value to be falsy, instead received
      [[1.5]]
```

MyComponent
```
<template>
  <div class="energy-tariff mb-5">
    <small class="mb-0">{{ content.monitoring_production_graph_energytariff_label }}</small>
    <div class="input-group d-flex">
      <money v-model="price"
             v-bind="money"
             type="text"
             id="uname"
             class="form-control w-50"></money>
    </div>
    <b-form-invalid-feedback :class="{ 'd-block': $v.price.$error}">
      <!-- <div v-if="!$v.price.required">{{ this.content.login_error_invalid_email }}</div> -->
      <div v-if="!$v.price.between"
           id="betweenError">{{ this.content.monitoring_production_graph_energytariff_error_highvalue }}</div>
    </b-form-invalid-feedback>
  </div>
</template>

<script>
import { Money } from 'v-money';
import { required, between } from 'vuelidate/lib/validators';

export default {
  name: 'MyComponent',
  props: ['value'],
  components: {
    Money
  },
  data() {
    return {
      price: this.value,
      money: {
        decimal: ',',
        thousands: '.',
        prefix: '€ ',
        suffix: '',
        precision: 2,
        masked: false
      }
    };
  },
  validations: {
    price: {
      required,
      between: between(0, 1)
    }
  },
  watch: {
    price(newValue, oldValue) {
      console.log(oldValue, newValue);
      // check if value differs from previous version
      // we watch because v-money fires a lot of @input
      // events, so we compare values
      if (newValue && newValue !== oldValue) {
        this.$v.$touch();

        // if valid, emit value
        if (this.$v.price.$invalid) {
          return;
        }
        this.$emit('input', newValue);
      }
    }
  }
};
</script>
```

any clue?

**Comment by pjo336** [comment]
whomp whomp

**Comment by perezd** [comment]
any updates on this? I am experiencing a similar thing. I tried the advice here: https://github.com/vuelidate/vuelidate/issues/521 and it didn't work in my case. It seems like the property validation booleans are not synchronized as expected.
